"""Byte-parity test: Python engine vs. TS engine.

Loads a JSON fixture produced by `scripts/dump_parity.ts` (positions +
legal moves + encoded boards + move indices generated by the TS engine)
and asserts the Python port reproduces every field identically.

This is the foundation for all downstream phases. If this test passes,
a PyTorch model trained on Python self-play games will see the same
state space the browser's TF.js model does.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

from chess_ai.encoding import NUM_PLANES, POLICY_SIZE, encode_board, move_to_index
from chess_ai.engine import ChessGameState, Move, get_legal_moves

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "parity_positions.json"


def _move_key(m: Move) -> tuple:
    return (m.from_pos.rank, m.from_pos.file, m.to_pos.rank, m.to_pos.file, m.promotion)


def _ts_move_key(m: dict) -> tuple:
    return (m["from"]["rank"], m["from"]["file"], m["to"]["rank"], m["to"]["file"], m.get("promotion"))


@pytest.fixture(scope="module")
def fixture_data() -> dict:
    if not FIXTURE_PATH.exists():
        pytest.skip(
            f"Fixture missing. Run `npm run dump-parity` from the project root first. "
            f"Expected at: {FIXTURE_PATH}"
        )
    with FIXTURE_PATH.open() as f:
        data = json.load(f)
    assert data["num_planes"] == NUM_PLANES, (
        f"Fixture NUM_PLANES={data['num_planes']} but Python expects {NUM_PLANES}"
    )
    assert data["policy_size"] == POLICY_SIZE
    return data


def test_fixture_has_positions(fixture_data: dict):
    assert len(fixture_data["positions"]) > 0


def test_legal_moves_parity(fixture_data: dict):
    """For every position, Python must compute the same set of legal moves."""
    mismatches = []
    for pos in fixture_data["positions"]:
        state = ChessGameState.from_dict(pos["state"])
        py_moves = get_legal_moves(state)
        py_set = {_move_key(m) for m in py_moves}
        ts_set = {_ts_move_key(m) for m in pos["legalMoves"]}
        if py_set != ts_set:
            mismatches.append(
                {
                    "id": pos["id"],
                    "only_py": py_set - ts_set,
                    "only_ts": ts_set - py_set,
                }
            )
            if len(mismatches) >= 3:
                break
    assert not mismatches, f"Legal-move mismatches (showing up to 3): {mismatches}"


def test_encoded_board_parity(fixture_data: dict):
    """For every position, Python's encode_board must match the TS output byte-for-byte."""
    for pos in fixture_data["positions"]:
        state = ChessGameState.from_dict(pos["state"])
        py = encode_board(state)
        ts = np.asarray(pos["encodedBoard"], dtype=np.float32)
        assert py.shape == ts.shape, f"shape mismatch at id={pos['id']}: py={py.shape} ts={ts.shape}"
        # Encoding is exact (0/1 indicators + discrete ratios); no tolerance needed.
        if not np.array_equal(py, ts):
            diff_idx = np.where(py != ts)[0][:10]
            diffs = [(int(i), float(py[i]), float(ts[i])) for i in diff_idx]
            raise AssertionError(
                f"encode_board mismatch at id={pos['id']}: first diffs (idx, py, ts)={diffs}"
            )


def test_move_index_parity(fixture_data: dict):
    """For each legal move, move_to_index must produce the same policy index."""
    for pos in fixture_data["positions"]:
        state = ChessGameState.from_dict(pos["state"])
        is_white = state.currentTurn == "white"
        ts_moves = pos["legalMoves"]
        ts_indices = pos["legalMoveIndices"]
        assert len(ts_moves) == len(ts_indices)
        for ts_move, ts_idx in zip(ts_moves, ts_indices):
            py_move = Move.from_dict(ts_move)
            py_idx = move_to_index(py_move, is_white)
            assert py_idx == ts_idx, (
                f"move_to_index mismatch at id={pos['id']}, move={ts_move}: "
                f"py={py_idx} ts={ts_idx}"
            )
